version: '3.9'

services:

  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: wishlist
      POSTGRES_PASSWORD: wishlist
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      WISHLIST_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
      WISHLIST_SETTING_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

volumes:
  postgresql-data:
    driver: local
