version: '3.9'

services:

  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: wishlist
      POSTGRES_PASSWORD: wishlist
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    driver: local
